language: python
python: 3.6
sudo: false
cache: pip

python:
   - '2.7'
   - '3.4'
   - '3.5'
   - '3.6'

matrix:
   include:
      - TOX_ENV=docs
        python: '3.6'
      - TOX_ENV=lint
        python: '3.6'
  
install:
- pip install tox tox-travis
script:
- tox -e $TOX_ENV
cache:
  directories:
    - $HOME/.cache/pip
