language: python
sudo: false
cache: pip

python:
   - '2.7'
   - '3.4'
   - '3.5'
   - '3.6'

matrix:
   include:
      - env: TOX_ENV=docs
        python: '3.6'
      - env: TOX_ENV=lint
        python: '3.6'
  
install:
- pip install tox tox-travis
script:
- tox
